[package]
name = "aoc"
edition = "2021"


[lib]
path = "src/lib.rs"

[[bin]]
name = "aoc"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
num = "0.4"
md5 = "0.7.0"
